// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutorPreClase.Infrastructure.Persistencia;

#nullable disable

namespace TutorPreClase.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928215909_CredencialesByok")]
    partial class CredencialesByok
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.AgenteIA", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreVisible")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlConsola")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("agente_ia", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Alternativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("alternativa", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.ArchivoContenido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreadoEn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId", "HashSha256")
                        .IsUnique();

                    b.ToTable("archivo_contenido", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Clase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AmpliacionPermitida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Inicio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("clase", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Conversacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgenteId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreadaEn")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("IntentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IntentoId")
                        .IsUnique();

                    b.HasIndex("ClaseId", "AlumnoId")
                        .IsUnique();

                    b.ToTable("conversacion", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.CredencialAgente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgenteId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaveCifrada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreadaEn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UltimoUsoEn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ultimos4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "AgenteId")
                        .IsUnique();

                    b.ToTable("credencial_agente", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("curso", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.DudaSinCobertura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreadoEn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespondidaConAmpliacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tema")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.ToTable("duda_sin_cobertura", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Examen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AbreEn")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CierraEn")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxIntentos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinutosLimite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModoFeedback")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Publicado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId")
                        .IsUnique();

                    b.ToTable("examen", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Intento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgenteId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Envio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamenId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Inicio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Porcentaje")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Puntaje")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamenId", "AlumnoId");

                    b.ToTable("intento", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Matricula", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RolEnCurso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("matricula", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.MensajeChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgenteId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreadoEn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fuentes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Herramienta")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreguntaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokensEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokensSalida")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsaAmpliacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId", "CreadoEn");

                    b.ToTable("mensaje_chat", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.NivelAlumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ActualizadoEn")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemasDebiles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId", "ClaseId")
                        .IsUnique();

                    b.ToTable("nivel_alumno", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.PaginaContenido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArchivoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pagina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("ArchivoId", "Pagina")
                        .IsUnique();

                    b.ToTable("pagina_contenido", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Pregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aprobada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamenId");

                    b.ToTable("pregunta", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.PreguntaReferencia", b =>
                {
                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaginaId")
                        .HasColumnType("TEXT");

                    b.HasKey("PreguntaId", "PaginaId");

                    b.HasIndex("PaginaId");

                    b.ToTable("pregunta_referencia", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.RespuestaIntento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlternativaId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreadoEn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IntentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoOriginalAlumno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("IntentoId", "PreguntaId")
                        .IsUnique();

                    b.ToTable("respuesta_intento", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentePreferido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Alternativa", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Pregunta", "Pregunta")
                        .WithMany("Alternativas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.ArchivoContenido", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Clase", "Clase")
                        .WithMany("Archivos")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Clase", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Curso", "Curso")
                        .WithMany("Clases")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Conversacion", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorPreClase.Domain.Entidades.Intento", "Intento")
                        .WithOne()
                        .HasForeignKey("TutorPreClase.Domain.Entidades.Conversacion", "IntentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Clase");

                    b.Navigation("Intento");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.CredencialAgente", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Examen", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Clase", "Clase")
                        .WithOne("Examen")
                        .HasForeignKey("TutorPreClase.Domain.Entidades.Examen", "ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Intento", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Examen", "Examen")
                        .WithMany()
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examen");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Matricula", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Curso", "Curso")
                        .WithMany("Matriculas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorPreClase.Domain.Entidades.Usuario", "Usuario")
                        .WithMany("Matriculas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.MensajeChat", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.PaginaContenido", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.ArchivoContenido", "Archivo")
                        .WithMany("Paginas")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Pregunta", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Examen", "Examen")
                        .WithMany("Preguntas")
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examen");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.PreguntaReferencia", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.PaginaContenido", "Pagina")
                        .WithMany()
                        .HasForeignKey("PaginaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorPreClase.Domain.Entidades.Pregunta", "Pregunta")
                        .WithMany("Referencias")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagina");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.RespuestaIntento", b =>
                {
                    b.HasOne("TutorPreClase.Domain.Entidades.Intento", "Intento")
                        .WithMany("Respuestas")
                        .HasForeignKey("IntentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutorPreClase.Domain.Entidades.Pregunta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intento");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.ArchivoContenido", b =>
                {
                    b.Navigation("Paginas");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Clase", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Examen");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Curso", b =>
                {
                    b.Navigation("Clases");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Examen", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Intento", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Pregunta", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("Referencias");
                });

            modelBuilder.Entity("TutorPreClase.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
